from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QMessageBox

from main import *


class Ui_label_initial_vertex(object):
    def __init__(self):
        self.__my_algo = MyAlgorithm()
        self.__closed_walks1 = []
        self.__closed_walks2 = []
        self.__time1 = 0
        self.__time2 = 0
        self.__k = 0

    def generate_graph_gui(self):
        self.__time1 = 0
        self.__time2 = 0
        res = self.__my_algo.generate_graph(int(self.txt_initial_vertex.text()), int(self.txt_numberof_node.text())
                                            , int(self.txt_numberof_edge.text()), 13)
        self.__k = int(self.txt_k.text())
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Graph Generated Successfully!")
        msgBox.setWindowTitle("Information")
        msgBox.setStandardButtons(QMessageBox.Ok)
        # msgBox.buttonClicked.connect(msgButtonClick)
        print(res)

        returnValue = msgBox.exec()
        if returnValue == QMessageBox.Ok:
            print('OK clicked')
            image = QPixmap("outputs/demo13.png")
            self.graph_image.setPixmap(image)
            if len(res) < 1:
                self.paralel_edges.setText("There is no parallel edge!")
            else:
                self.paralel_edges.setText(str(res)[1:-1])

    def run_heuristic(self):
        self.__time1 = 0
        res = self.__my_algo.my_algorithm(self.__k)
        self.__time1 = res[1]
        self.time_heuristic.setText("{:.18f}".format(res[1]) + "s")
        cycles = res[0]
        for e in cycles:
            self.cycles_heuristic.insertPlainText(str(e)[1:-1] + "\n")
        maxx = cycles[0]
        lenth = maxx['length']
        self.cycles_heuristic.insertPlainText("Maximum length: " + str(lenth) + "\n")
        if self.__time1 > 0 and self.__time2 > 0:
            self.time_diff.setText("{:.20f}".format(self.__time2 - self.__time1) + "s")

    def run_exhaustive(self):
        self.__time2 = 0
        res = self.__my_algo.simple_algo()
        self.__time2 = res[1]
        self.time_exhaustive.setText("{:.18f}".format(res[1]) + "s")
        cycles = res[0]
        for e in cycles:
            self.cycles_exhaustive.insertPlainText(str(e)[1:-1] + "\n")
        maxx = cycles[0]
        lenth = maxx['length']
        self.cycles_exhaustive.insertPlainText("Maximum length: " + str(lenth) + "\n")
        if self.__time1 > 0 and self.__time2 > 0:
            self.time_diff.setText("{:.20f}".format(self.__time2 - self.__time1) + "s")

    def setupUi(self, label_initial_vertex):
        label_initial_vertex.setObjectName("label_initial_vertex")
        label_initial_vertex.resize(1370, 730)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../gui/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        label_initial_vertex.setWindowIcon(icon)
        label_initial_vertex.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(label_initial_vertex)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generate_graph = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate_graph.setGeometry(QtCore.QRect(180, 140, 101, 31))
        self.btn_generate_graph.setObjectName("btn_generate_graph")

        self.txt_k = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_k.setGeometry(QtCore.QRect(260, 100, 161, 21))
        self.txt_k.setText("")
        self.txt_k.setObjectName("txt_k")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 100, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_initial_vertex = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_initial_vertex.setGeometry(QtCore.QRect(330, 60, 91, 21))
        self.txt_initial_vertex.setText("")
        self.txt_initial_vertex.setObjectName("txt_initial_vertex")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_numberof_edge = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numberof_edge.setGeometry(QtCore.QRect(130, 100, 81, 21))
        self.txt_numberof_edge.setText("")
        self.txt_numberof_edge.setObjectName("txt_numberof_edge")
        self.txt_numberof_node = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numberof_node.setGeometry(QtCore.QRect(130, 60, 81, 21))
        self.txt_numberof_node.setText("")
        self.txt_numberof_node.setObjectName("txt_numberof_node")
        self.label_node = QtWidgets.QLabel(self.centralwidget)
        self.label_node.setGeometry(QtCore.QRect(10, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_node.setFont(font)
        self.label_node.setObjectName("label_node")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.graph_image = QtWidgets.QLabel(self.centralwidget)
        self.graph_image.setGeometry(QtCore.QRect(10, 210, 421, 431))
        self.graph_image.setText("")
        self.graph_image.setObjectName("graph_image")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(440, 50, 450, 591))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_run_heuristic = QtWidgets.QPushButton(self.groupBox)
        self.btn_run_heuristic.setGeometry(QtCore.QRect(10, 50, 141, 41))
        self.btn_run_heuristic.setObjectName("btn_run_heuristic")
        self.cycles_heuristic = QtWidgets.QTextEdit(self.groupBox)
        self.cycles_heuristic.setEnabled(True)
        self.cycles_heuristic.setGeometry(QtCore.QRect(10, 150, 431, 431))
        self.cycles_heuristic.setReadOnly(True)
        self.cycles_heuristic.setPlaceholderText("")
        self.cycles_heuristic.setObjectName("cycles_heuristic")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(190, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.time_heuristic = QtWidgets.QLabel(self.groupBox)
        self.time_heuristic.setGeometry(QtCore.QRect(290, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.time_heuristic.setFont(font)
        self.time_heuristic.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time_heuristic.setObjectName("time_heuristic")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(910, 50, 450, 591))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_run_exhaustive = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_run_exhaustive.setGeometry(QtCore.QRect(10, 50, 141, 41))
        self.btn_run_exhaustive.setObjectName("btn_run_exhaustive")
        self.cycles_exhaustive = QtWidgets.QTextEdit(self.groupBox_2)
        self.cycles_exhaustive.setGeometry(QtCore.QRect(10, 150, 431, 437))
        self.cycles_exhaustive.setReadOnly(True)
        self.cycles_exhaustive.setObjectName("cycles_exhaustive")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(190, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.time_exhaustive = QtWidgets.QLabel(self.groupBox_2)
        self.time_exhaustive.setGeometry(QtCore.QRect(290, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.time_exhaustive.setFont(font)
        self.time_exhaustive.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time_exhaustive.setObjectName("time_exhaustive")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 650, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.paralel_edges = QtWidgets.QLabel(self.centralwidget)
        self.paralel_edges.setGeometry(QtCore.QRect(100, 650, 731, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.paralel_edges.setFont(font)
        self.paralel_edges.setText("")
        self.paralel_edges.setObjectName("paralel_edges")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(850, 650, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.time_diff = QtWidgets.QLabel(self.centralwidget)
        self.time_diff.setGeometry(QtCore.QRect(960, 651, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.time_diff.setFont(font)
        self.time_diff.setObjectName("time_diff")
        label_initial_vertex.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(label_initial_vertex)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1370, 21))
        self.menubar.setObjectName("menubar")
        label_initial_vertex.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(label_initial_vertex)
        self.statusbar.setObjectName("statusbar")
        label_initial_vertex.setStatusBar(self.statusbar)
        self.btn_run_heuristic.clicked.connect(lambda: self.run_heuristic())
        self.btn_generate_graph.clicked.connect(lambda: self.generate_graph_gui())
        self.btn_run_exhaustive.clicked.connect(lambda: self.run_exhaustive())

        self.retranslateUi(label_initial_vertex)
        QtCore.QMetaObject.connectSlotsByName(label_initial_vertex)

    def retranslateUi(self, label_initial_vertex):
        _translate = QtCore.QCoreApplication.translate
        label_initial_vertex.setWindowTitle(_translate("label_initial_vertex", "Minimum k-Chinese Postman Problem"))
        self.btn_generate_graph.setText(_translate("label_initial_vertex", "Generate Graph"))
        self.label.setText(_translate("label_initial_vertex", "Parameters"))
        self.label_2.setText(_translate("label_initial_vertex", "k :"))
        self.label_3.setText(_translate("label_initial_vertex", "Initial Vertex:"))
        self.label_4.setText(_translate("label_initial_vertex", "Number of Edge :"))
        self.label_node.setText(_translate("label_initial_vertex", "Number of Node :"))
        self.label_6.setText(_translate("label_initial_vertex", "Algorithms"))
        self.groupBox.setTitle(_translate("label_initial_vertex", "Heuristic Algorithm"))
        self.btn_run_heuristic.setText(_translate("label_initial_vertex", "Run \n"
"Heurisitic Algorithm"))
        self.label_8.setText(_translate("label_initial_vertex", "Cycles"))
        self.label_10.setText(_translate("label_initial_vertex", "Elapsed Time:"))
        self.time_heuristic.setText(_translate("label_initial_vertex", "0s"))
        self.groupBox_2.setTitle(_translate("label_initial_vertex", "Exhaustive Search Algorithm"))
        self.btn_run_exhaustive.setText(_translate("label_initial_vertex", "Run Exhaustive Search \n"
"Algorithm"))
        self.label_9.setText(_translate("label_initial_vertex", "Cycles"))
        self.label_11.setText(_translate("label_initial_vertex", "Elapsed Time:"))
        self.time_exhaustive.setText(_translate("label_initial_vertex", "0s"))
        self.label_14.setText(_translate("label_initial_vertex", "Generated Graph"))
        self.label_15.setText(_translate("label_initial_vertex", "Parallel Edges:"))
        self.label_16.setText(_translate("label_initial_vertex", "Time Difference:"))
        self.time_diff.setText(_translate("label_initial_vertex", "0s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    label_initial_vertex = QtWidgets.QMainWindow()
    ui = Ui_label_initial_vertex()
    ui.setupUi(label_initial_vertex)
    label_initial_vertex.show()
    sys.exit(app.exec_())
